on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Node.js 20
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 2: Check out the latest code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Deploy the UserRequestLambda function
      - name: Install dependencies for UserRequestLambda
        run: |
          cd UserRequestLambda
          npm install openai

      - name: Zip UserRequestLambda function
        run: |
          cd UserRequestLambda
          zip -r ../UserRequestLambda.zip .

      - name: Deploy UserRequestLambda to AWS
        run: |
          aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --zip-file fileb://UserRequestLambda.zip

      # Step 5: Deploy the QueueProcessingLambda function
      - name: Install dependencies for QueueProcessingLambda
        run: |
          cd QueueProcessingLambda
          npm install

      - name: Zip QueueProcessingLambda function
        run: |
          cd QueueProcessingLambda
          zip -r ../QueueProcessingLambda.zip .

      - name: Deploy QueueProcessingLambda to AWS
        run: |
          aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME_2 }} --zip-file fileb://QueueProcessingLambda.zip
